insert into pet(id, age, gender, image_name, name,parent_id,race, parent_weight ) 
values 
(1, 12,'M','image1.jpg','Negao', 1, 'Cane corso', 2),
(2, 11,'F','image2.jpg','Neguinha', 2, 'Cane corso', 2),
(3, 9,'F','image2.jpg','Nina', 2, 'Cane corso', 3),
(4, 9,'F','image2.jpg','Nila', 2, 'Cane corso', 4),
(5, 9,'M','image1.jpg','Nino', 2, 'Cane corso', 5),
(6, 6,'M','image1.jpg','Boo', 3, 'Cane corso', 5),
(7, 6,'M','image1.jpg','Scooby', 3, 'Cane corso', 4),
(8, 6,'M','image1.jpg','Clifford', 3, 'Cane corso', 3),
(9, 6,'F','image2.jpg','Laika', 4, 'Cane corso', 4),
(10, 2,'M','image1.jpg','Nhoque ', 9, 'Cane corso', 5),
(11, 2,'M','image1.jpg','Quindim', 9, 'Cane corso', 2),
(12, 2,'F','image2.jpg','Panqueca', 9, 'Cane corso', 5),
(13, 2,'F','image2.jpg','Pacoca', 9, 'Cane corso', 7),
(14, 2,'F','image2.jpg','Bisteca', 9, 'Cane corso', 8),
(15, 2,'M','image1.jpg','Torresmo ', 9, 'Cane corso', 9),
(16, 7,'M','image1.jpg','Negao I ', 1, 'Cane corso', 4),
(17, 7,'F','image1.jpg','Neginha II ', 1, 'Cane corso', 4),
(18, 7,'F','image1.jpg','Neginha III', 1, 'Cane corso', 4),
(19, 6,'F','image1.jpg','Neginha IV', 1, 'Cane corso', 4),
(20, 3,'M','image1.jpg','Torresmo II', 3, 'Cane corso', 4),
(21, 2,'F','image1.jpg','Princesa I', 4, 'Cane corso', 4),
(22, 1,'F','image1.jpg','Princesa II', 4, 'Cane corso', 4),
(23, 5,'F','image1.jpg','Princesa III', 4, 'Cane corso', 4);